import { Dimensions, StyleSheet } from 'react-native';
import Constants from '../../Variables/colors.variables';

const Styles = StyleSheet.create({
  container: {
    backgroundColor: Constants.appBackgroundColor,
    alignItems: 'flex-start',
    flex: 1,
  },
  buttonSection: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 12,
    marginVertical: 16,
  },
  active: {
    backgroundColor: Constants.primaryColor,
    width: Dimensions.get('window').width / 3 - 12,
    borderRadius: 7,
    paddingHorizontal: 24,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
  },
  inactive: {
    backgroundColor: Constants.appBackgroundColor,
    width: Dimensions.get('window').width / 3 - 12,
    borderRadius: 7,
    paddingHorizontal: 24,
    paddingVertical: 12,
    textAlign: 'center',
    alignItems: 'center',
    justifyContent: 'center',
  },
  activeButtonText: {
    fontSize: 15,
    fontFamily: 'Poppins-Medium',
    color: 'white',
    textAlign: 'center',
  },
  inactiveButtonText: {
    fontSize: 15,
    fontFamily: 'Poppins-Medium',
    color: '#646466',
    textAlign: 'center',
  },
  generalSection: {
    marginHorizontal: 16,
    marginVertical: 8,
  },
  codSection: {
    marginHorizontal: 16,
    marginVertical: 8,
  },
  codCard: {
    backgroundColor: 'white',
    borderRadius: 12,
    width: Dimensions.get('window').width - 32,
    flexDirection: 'row',
    padding: 16,
    marginVertical: 8,
  },
  codLeftSection: {
    width: 34,
    height: 34,
    borderRadius: 20,
    backgroundColor: '#CEEFFB',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 16,
  },
  codName: {
    fontSize: 15,
    fontFamily: 'Poppins-Medium',
    color: '#222224',
    textAlign: 'center',
  },
  codAmount: {
    color: '#21B535',
    fontSize: 13,
    fontFamily: 'Poppins-Medium',
  },
  generalCard1: {
    backgroundColor: '#FDF5DE',
    padding: 15,
    borderRadius: 12,
    alignItems: 'center',
    textAlign: 'center',
    minHeight: 90,
    width: Dimensions.get('window').width - 32,
    marginVertical: 8,
  },
  generalCard2: {
    backgroundColor: '#FFE4E4',
    padding: 15,
    borderRadius: 12,
    alignItems: 'center',
    textAlign: 'center',
    minHeight: 90,
    width: Dimensions.get('window').width - 32,
    marginVertical: 8,
  },
  generalCard3: {
    backgroundColor: '#E5F8E2',
    padding: 15,
    borderRadius: 12,
    alignItems: 'center',
    textAlign: 'center',
    minHeight: 90,
    width: Dimensions.get('window').width - 32,
    marginVertical: 8,
  },
  generalHeading: {
    fontSize: 15,
    fontFamily: 'Poppins-Medium',
    color: '#222224',
    textAlign: 'center',
    marginBottom: 6,
  },
  generalSubHeading: {
    fontSize: 20,
    fontFamily: 'Poppins-Medium',
    color: '#222224',
    textAlign: 'center',
    marginBottom: 6,
  },
});

export default Styles;
